kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: contodo
          image: bipeshadhikari/todo
          ports:
            - containerPort: 3000
